build:
  maxIssues: 9999
  excludeCorrectable: false

config:
  validation: false
  warningsAsErrors: false

style:
  active: false

naming:
  active: false

complexity:
  active: false

comments:
  active: false

potential-bugs:
  active: false

exceptions:
  active: false

performance:
  active: false

empty-blocks:
  active: false

coroutines:
  active: false